import { QueryInterface } from 'sequelize';

export default {
  up: async (queryInterface: QueryInterface) => {
    // Update existing prompts with sample essays
    await queryInterface.bulkUpdate('prompts', {
      sampleEssay: 'It is often argued that technological advancements have complicated our lives, whereas others contend that they have simplified them. In my opinion, although technology can be challenging to adapt to initially, it ultimately makes our lives easier in many ways. This essay will discuss both perspectives before presenting my viewpoint.\n\nOn the one hand, there are several reasons why some people believe technology has made life more complicated. Firstly, the rapid pace of technological change means that people constantly need to learn new skills and adapt to new devices. For example, older people often struggle with smartphones and computers, leading to frustration and feelings of inadequacy. Secondly, technology can create new problems such as privacy concerns and cyber security threats. People worry about their personal data being hacked or misused, which adds a layer of complexity to daily life.\n\nOn the other hand, technology has undoubtedly simplified many aspects of modern life. Communication is a prime example; video calls and instant messaging allow us to connect with anyone anywhere at virtually no cost. This has strengthened relationships and made international collaboration easier. Furthermore, technology has automated many tedious tasks. For instance, online banking and shopping apps save time and reduce the need for physical travel, making daily routines more efficient.\n\nIn conclusion, while technology does present some challenges, particularly for those less familiar with it, the benefits far outweigh the drawbacks. The key is to embrace technological change and use it to enhance rather than complicate our lives.'
    }, {
      title: 'Technology and Communication'
    });

    await queryInterface.bulkUpdate('prompts', {
      sampleEssay: 'The government should invest more money in environmental protection rather than in economic development. To what extent do you agree or disagree?\n\nThere is ongoing debate about whether governments should prioritize environmental protection over economic development. While some argue that economic growth should take precedence, I strongly believe that environmental protection is equally important and should be given equal consideration.\n\nThose who favor economic development argue that it provides jobs, raises living standards, and reduces poverty. Developing countries need economic growth to improve infrastructure, healthcare, and education. Furthermore, economic development can fund environmental initiatives once countries become wealthier. For example, many developed nations began serious environmental protection only after achieving economic prosperity.\n\nHowever, I believe environmental protection should not be sacrificed for economic growth. Firstly, environmental degradation has serious long-term consequences. Climate change, deforestation, and pollution threaten human health, agriculture, and biodiversity. The costs of environmental damage often outweigh the benefits of short-term economic gains. Moreover, sustainable development is possible through green technologies and renewable energy, which can create jobs while protecting the environment.\n\nFurthermore, environmental problems do not respect national borders. Actions in one country can affect global climate patterns and ecosystems. International cooperation is essential, and wealthy nations have a responsibility to help developing countries adopt sustainable practices.\n\nIn conclusion, while economic development is important, it should not come at the expense of environmental protection. Governments should pursue sustainable development that balances economic growth with environmental stewardship.'
    }, {
      title: 'Environmental Protection'
    });

    await queryInterface.bulkUpdate('prompts', {
      sampleEssay: 'Some people think that schools should focus more on academic subjects while others believe that schools should also teach practical skills. Discuss both views and give your opinion.\n\nThere is considerable debate about whether computers and the internet are more important than traditional schooling for children\'s education. While technology offers numerous advantages, I believe that school teachers remain essential for effective learning.\n\nOn one hand, computers and the internet provide access to vast amounts of information and learning resources. Children can learn at their own pace through interactive online courses and educational websites. Technology also offers personalized learning experiences that adapt to individual needs. Moreover, online education can be more cost-effective and flexible, allowing students to study from anywhere at any time.\n\nHowever, traditional schooling with teachers offers irreplaceable benefits that technology cannot provide. Teachers offer guidance, motivation, and emotional support that are crucial for children\'s development. They can identify when students are struggling and provide personalized attention. Furthermore, schools teach important social skills and foster interaction between students from diverse backgrounds.\n\nIn my view, the most effective education combines both approaches. Technology can enhance traditional learning by providing additional resources and interactive tools. Teachers can use computers to create engaging lessons and help students develop digital literacy skills. The ideal system integrates technology as a tool to support, rather than replace, traditional teaching methods.\n\nTo conclude, while computers and the internet offer valuable educational opportunities, school teachers play an irreplaceable role in children\'s learning. The best approach combines the strengths of both traditional and digital education.'
    }, {
      title: 'Education System'
    });

    await queryInterface.bulkUpdate('prompts', {
      sampleEssay: 'The chart below shows the percentage of households in owned and rented accommodation in England and Wales between 1918 and 2011. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.\n\nThe chart illustrates the proportion of households living in owned and rented accommodation in England and Wales from 1918 to 2011. Overall, the percentage of owner-occupied homes increased significantly over the period, while rented accommodation declined considerably.\n\nIn 1918, approximately 23% of households owned their homes, compared to 77% who rented. This trend reversed dramatically over the next century. By 2001, owner occupation had risen to 69%, while private renting had fallen to 10%. Social renting (from local authorities or housing associations) peaked at around 29% in 1981 but declined to 17% by 2011.\n\nThe most striking change occurred in owner occupation, which grew steadily from 23% in 1918 to reach a peak of 70% in 2001, before slightly declining to 65% in 2011. This increase was largely at the expense of private renting, which fell from 77% in 1918 to 17% by 2011.\n\nSocial renting showed more fluctuation, starting at zero in 1918, rising to 29% by 1981, then declining to 17% by the end of the period. This pattern reflects changes in government housing policies and economic conditions over the decades.\n\nIn summary, the data shows a clear shift from renting to owner occupation in England and Wales over nearly a century, with owner occupation becoming the dominant form of housing tenure by the early 21st century.'
    }, {
      title: 'Urban Population Growth'
    });

    await queryInterface.bulkUpdate('prompts', {
      sampleEssay: 'The graphs below show the percentage of Internet users in different age groups in Australia from 1994 to 2009, and the percentage of people who purchased goods online in Australia between 1994 and 2009. Summarise the information by selecting and reporting the main features, and make comparisons where relevant.\n\nThe line graph illustrates Internet usage among different age groups in Australia from 1994 to 2009, while the bar chart shows the percentage of Australians who made online purchases during the same period.\n\nRegarding Internet usage by age, the 14-17 age group consistently had the highest percentage throughout the period, starting at around 2% in 1994 and reaching approximately 90% by 2009. The 18-24 group followed a similar pattern but at lower levels, beginning at about 1% and ending at around 80%.\n\nOlder age groups showed more gradual increases. Those aged 25-34 started at nearly 0% and reached about 75% by 2009. The 35-49 group began at 0% and ended at approximately 60%, while those aged 50-64 started at 0% and reached around 45%. People over 65 had the lowest usage, starting at 0% and ending at just over 20%.\n\nThe bar chart shows online shopping adoption rising from 10% in 1994 to approximately 60% in 2009, with the most significant growth occurring between 2003 and 2009.\n\nOverall, younger Australians adopted Internet technology much faster than older generations, with teenagers leading the way. Online shopping also became increasingly popular over the 15-year period, though adoption rates were lower than basic Internet usage.'
    }, {
      title: 'Internet Usage Statistics'
    });

    await queryInterface.bulkUpdate('prompts', {
      sampleEssay: 'Many people find it difficult to balance work and other parts of their lives. What are the reasons for this? What can be done to help people achieve a better work-life balance?\n\nThere are several reasons why achieving work-life balance has become increasingly challenging in modern society. This essay will discuss these causes and propose some solutions.\n\nOne primary reason is the demanding nature of modern work. Many jobs require employees to work long hours, often extending beyond the standard 40-hour workweek. In competitive industries, people feel pressured to work overtime to meet deadlines and demonstrate commitment to their employers. Additionally, technology has blurred the boundaries between work and personal life. Smartphones and laptops enable constant connectivity, making it difficult for people to disconnect from work even during leisure time.\n\nAnother factor is economic pressure. In many countries, the cost of living has risen significantly, requiring both partners in a household to work full-time to maintain their standard of living. This leaves little time for family responsibilities, childcare, or personal pursuits. Furthermore, the gig economy and freelance work have created uncertainty, leading people to take on multiple jobs or work irregular hours to ensure financial stability.\n\nTo address these issues, several measures can be implemented. Employers should promote flexible working arrangements, such as remote work options and flexible hours. This would allow employees to better manage their time and reduce commuting stress. Governments could also introduce policies that limit maximum working hours and guarantee paid parental leave.\n\nAdditionally, individuals should learn to set boundaries and prioritize self-care. This might involve turning off work notifications during personal time or delegating tasks when possible. Companies can also provide training on time management and stress reduction techniques.\n\nIn conclusion, while modern work demands and economic pressures make work-life balance challenging, various solutions exist at individual, organizational, and governmental levels. Achieving better balance requires commitment from all stakeholders to create a more sustainable and healthy work culture.'
    }, {
      title: 'Work-Life Balance'
    });
  },

  down: async (queryInterface: QueryInterface) => {
    await queryInterface.bulkUpdate('prompts', {
      sampleEssay: null
    }, {});
  },
};